#!/usr/bin/env bash

removing_package() {
    local package=$1
    local description=$2

    echo "------------------------------------------------"
    echo "Removing: $description"
    echo "Package: $package"
    
    adb shell pm uninstall --user 0 "$package"
    
    echo "Done."
}

removing_package "com.miui.weather2" "Mi Weather"
removing_package "com.xiaomi.midrop" "ShareMe"
removing_package "com.xiaomi.scanner" "Scanner"
removing_package "com.miui.notes" "Mi Notes"
removing_package "com.miui.compass" "Mi Compass"
removing_package "com.miui.calculator" "Mi Calculator"
removing_package "com.miui.screenrecorder" "Screen Recorder"
removing_package "com.xiaomi.mipicks" "Mi Picks / GetApps"
removing_package "org.mipay.android.manager" "Mi Pay Manager"
removing_package "com.mi.global.shop" "Mi Store / Shop"
removing_package "com.mi.appfinder" "Mi App Finder"
removing_package "com.einnovation.temu" "Temu (App de Compras)"
removing_package "com.linkedin.android" "LinkedIn"
removing_package "cn.wps.xiaomi.abroad.lite" "WPS Office Lite"
removing_package "com.facebook.system" "Facebook System"
removing_package "com.facebook.services" "Facebook Services"
removing_package "com.amazon.appmanager" "Amazon App Manager"
removing_package "com.sfr.android.sfrjeux" "Jogos da Operadora SFR"
removing_package "com.orange.update" "Serviço de Atualização da Orange"
removing_package "com.miui.phone.carriers.overlay.vodafone" "Overlay da Vodafone"
removing_package "com.miui.phone.carriers.overlay.h3g" "Overlay da H3G (Three)"
removing_package "com.xiaomi.joyose" "Joyose (Coleta de dados e limitação de performance)"
removing_package "com.xiaomi.ugd" "Xiaomi User Guide Daemon"
removing_package "com.miui.misightservice" "Mi Sight (Diagnósticos em segundo plano)"
removing_package "com.miui.micloud.sdk" "Xiaomi Cloud SDK"
removing_package "com.xiaomi.xmsf" "Xiaomi Service Framework"
removing_package "com.xiaomi.xmsfkeeper" "Xiaomi Service Framework Keeper"
removing_package "com.miui.system.overlay" "System Overlay (Muitas vezes usado para Ads)"
removing_package "com.mi.globallayout" "Global Layout (Customizações de região/publicidade)"
removing_package "com.xiaomi.abtest" "Xiaomi A/B Testing"
removing_package "com.android.browser" "Navegador Padrão MIUI"
removing_package "com.android.calendar" "Calendário da Xiaomi (com.xiaomi.calendar)"
removing_package "com.android.deskclock" "Relógio da Xiaomi"
removing_package "com.android.soundrecorder" "Gravador de Voz"
removing_package "com.android.apps.tag" "NFC Tags App"
removing_package "com.miui.qr" "Leitor de QR Code MIUI"
removing_package "com.miui.phrase" "Frases Frequentes (Teclado MIUI)"
removing_package "com.orange.update" "Orange Update (Operadora)"
removing_package "com.miui.phone.carriers.overlay.vodafone" "Vodafone Carrier Overlay"
removing_package "com.miui.phone.carriers.overlay.h3g" "H3G/Three Carrier Overlay"
removing_package "com.ironsource.appcloud.oobe.hutchison" "Ironsource AppCloud (Instalador silencioso)"
removing_package "com.microsoftsdk.crossdeviceservicebroker" "Microsoft Cross Device Broker"
removing_package "com.google.android.apps.docs" "Google Drive"
removing_package "com.google.android.apps.maps" "Google Maps"
removing_package "com.google.android.apps.messaging" "Google Mensagens"
removing_package "com.google.android.apps.restore" "Google Restore"
removing_package "com.google.android.feedback" "Google Feedback"
removing_package "com.google.android.tts" "Google Text-to-Speech"
removing_package "com.miui.accessibility" "Xiaomi Accessibility (Se não usar gestos de acessibilidade)"
removing_package "com.mi.global.bbs" "Xiaomi Community App"
removing_package "com.xiaomi.payment" "Xiaomi Payment Services (Mi Pay)"
removing_package "com.xiaomi.account" "Xiaomi Account (Remova se NÃO usa Mi Cloud/Sincronização)"
removing_package "com.miui.extraphoto" "Recursos extras da Galeria (filtros/IA)"
removing_package "com.miui.bugreport" "Mi Bug Report"
removing_package "com.miui.miservice" "Xiaomi Service Framework Extras"
removing_package "com.bsp.logmanager" "Log Manager do Sistema"
